### ISSUE TITLE
Number of cpu cores not recognized, resulting in numerous high load notifications

### ISSUE THREAD

**Issue by x2k13** [DesktopECHO/Pi-hole-for-Android#19]
My setup:
Samsung Galaxy S4 (GT-I9505) (Snapdragon 600, quadcore SoC)
crDroid 7.21 (LOS 18.1/Android 11)
Magisk 25.2
Linux Deploy 2.60
BusyBox (meefik) 1.34.1

Pi-hole is set up and running, resolving & blocking, all good so far.

The only thing that's a bit frustrating is the constantly popping up "high load" notifications.

It seems that Pi-hole (or one of its sub-systems) doesn't recognize all usable cores provided by the device, like 1 cpu/4 cores, instead sees just 1 cpu/1 core but the load values indicate that all cores are indeed used, but somehow Pi-hole doesn't understand this and panics because the 1 cpu/1 core it sees is always on ~4x load. 

Any ideas how to change this behaviour? I don't have that on a RPi running Pi-hole.

Thank you for your time and effort!

![Screenshot_20220913-072904_Vivaldi Browser](https://user-images.githubusercontent.com/13673423/189816632-4226c021-ee88-41b1-be2a-d946d79ddb50.png)

**Comment by DesktopECHO** [comment]
Hi... looks like a similar issue reported here: [https://github.com/DesktopECHO/Pi-hole-for-Android/issues/2](https://github.com/DesktopECHO/Pi-hole-for-Android/issues/2)

Some Android devices will show strange load averages even if the device isn't busy.

**Comment by x2k13** [comment]
Good to know. When I check average load on DevCheck, it correctly shows load values of all 4 cores.
Might be interesting to find out what in the tool chain (Linux Deploy?) is having problems with handing that info over to Pi-hole, though. Anyway, thanks for the reply!

**Comment by DesktopECHO** [comment]
Turns out there's an option to disable FTL load average checking so it's easy enough to deal with:

Edit `/usr/local/bin/p4a-install`

Go to the `# Fixups` section and add the following line:

`sed -i 's/config.check.load = read_bool(buffer, true)/config.check.load = read_bool(buffer, false)/g' src/config.c`

Run `p4a-install` and it will rebuild a pihole-FTL binary that doesn't check load average.

Seeing as how these load averages are silly made-up numbers on many Android devices, the following change keeps the load lights green on the front page:

`sed -i 's/$nproc)/1337)/g' /var/www/html/admin/scripts/pi-hole/php/sidebar.php`  

![image](https://user-images.githubusercontent.com/33142753/190055235-a51784a3-64a4-4b11-a510-5488b6d00a0f.png)

Now everything looks clean.

**Comment by x2k13** [comment]
Thanks for the detailed info! 🙂
